# Generated by Django 3.2 on 2021-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_comments',
            field=models.BooleanField(default=True),
        ),
    ]
