# Generated by Django 3.1.7 on 2021-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='describe me'),
            preserve_default=False,
        ),
    ]
