# Generated by Django 3.1.7 on 2021-04-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210412_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Meme'), (2, 'Propaganda'), (3, 'Engineering'), (4, 'Programming')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='headerimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
