# Generated by Django 3.1.7 on 2021-04-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210412_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='headerimg',
            new_name='header_image',
        ),
    ]
